version: "3"
services:
  HubService:
    image: selenium/hub:4.23.1-20240813
    container_name: seleniumHub
    ports:
      - "3000:4444"
      - "4442:4442"
      - "4443:4443"

  ChromeService:
    image: selenium/node-chrome:4.23.1-20240813
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService

  FirefoxService:
    image: selenium/node-firefox:4.23.1-20240813
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService

  EdgeService:
    image: selenium/node-edge:4.23.1-20240813
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService


# version: "3"
# services:
#   selenium-hub:
#     image: selenium/hub:4.23.1-20240813
#     container_name: selenium-hub
#     ports:
#       - "3000:4444"
#       - "4442:4442"
#       - "4443:4443"

#   chrome:
#     image: selenium/node-chrome:4.23.1-20240813
#     shm_size: 2gb
#     depends_on:
#       - selenium-hub
#     environment:
#       - SE_EVENT_BUS_HOST=selenium-hub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_NODE_MAX_SESSIONS=3
#       - SE_VNC_NO_PASSWORD=1

#   firefox:
#     image: selenium/node-firefox:4.23.1-20240813
#     shm_size: 2gb
#     depends_on:
#       - selenium-hub
#     environment:
#       - SE_EVENT_BUS_HOST=selenium-hub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_NODE_MAX_SESSIONS=3
#       - SE_VNC_NO_PASSWORD=1

  # edge:
  #   image: selenium/node-edge:4.23.1-20240813
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - SE_NODE_MAX_SESSIONS=1

  
      

  # MavenTestService:
  #   image: padminikadhir/myselgridfwwithdata
  #   container_name: mavenTestRunner
  #   command: mvn -f /home/docker_seleniumgridFW_withdata/pom.xml clean test
  #   environment:
  #     - EXCEL_FILE_PATH=/data/userlogindata.xlsx  # Excel file path as an environment variable
  #   depends_on:
  #     - selenium-hub
  #     - chrome
  #     - firefox
  #     - edge
  #   volumes:
  #     - "/d/Docker_Practice/Docker_SeleniumGrid/docker_seleniumgrid_withdata/data:/data"

# version: "3"
# services:
#   HubService:
#     image: selenium/hub:4.0.0-rc-2-20210930
#     container_name: seleniumHub
#     ports:
#       - "3000:4444" 
#       - "4442:4442"
#       - "4443:4443"

#   ChromeService:
#     image: selenium/node-chrome:4.0.0-rc-2-20210930
#     shm_size: "2gb"
#     ports:
#       - "5900"  
#       - "7900"
#     environment:
#       - SE_EVENT_BUS_HOST=seleniumHub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_NODE_MAX_SESSIONS=9
#     depends_on:
#       - HubService

#   FirefoxService:
#     image: selenium/node-firefox:4.0.0-rc-2-20210930
#     shm_size: "2gb"
#     ports:
#       - "5900"
#       - "7900"
#     environment:
#       - SE_EVENT_BUS_HOST=seleniumHub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_NODE_MAX_SESSIONS=9
#     depends_on:
#       - HubService

#   EdgeService:
#     image: selenium/node-edge:4.0.0-rc-2-20210930
#     shm_size: "2gb"
#     ports:
#       - "5900"
#       - "7900"
#     environment:
#       - SE_EVENT_BUS_HOST=seleniumHub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_NODE_MAX_SESSIONS=2
#     depends_on:
#       - HubService
